A:	.WORD	5. ;
B:	.WORD	5. 
C:	.WORD	5.
D:	.WORD   5.
E:	.WORD   5.
F:	.WORD   6.
G:   .WORD  0.
H:   .WORD  2.
I:   .WORD  16.

START:
CLR     A          ; Register mode
CLR     (R1)        ; Register deferred - R1 contain add. of B
CLR     (R2)+       ; Autoincrement - R2 contain add. of C
CLR     @(R3)+      ; Autoincrement deferred -R3 contain add. of F and F cantain add. of C
CLR     -(R4)       ; Autodecrement - R4 contain add. of D+2
CLR     @-(R5)      ; Autodecrement deferred - R5 contain add of I and I contain add of H 
CLR     2(R3)       ; Index - R3 contain add. of E-2 
CLR     @0(R0)      ; Index deferred R0 cantain add. of G+0

WEND:
		.END	START